### ISSUE TITLE
mnist_addition git:(master)   python slash_mnist_addition.py : No such file or directory: 'data/labels/train_data.txt'

### ISSUE THREAD

**Issue by zdx3578** [askrix/SLASH#3]
(env_slash) ➜  mnist_addition git:(master) ✗ python slash_mnist_addition.py
start importing...
...done
Experiment's folder is dnn-normal-seed-4
Experiment parameters: {'use_spn': False, 'credentials': 'AS', 'seed': 4, 'lr': 0.005, 'bs': 100, 'epochs': 100, 'p_num': 8, 'drop_out': 0.0}
training with 44426 trainable params and 44426 params in total
networkAtom2MVPP
npp(digit(1,1,i1),(0,1,2,3,4,5,6,7,8,9))

networkAtom2MVPP
npp(digit(1,1,i2),(0,1,2,3,4,5,6,7,8,9))

Downloading http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz
Downloading http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz to ./data/MNIST/raw/train-images-idx3-ubyte.gz
9913344it [00:02, 3618342.17it/s]
Extracting ./data/MNIST/raw/train-images-idx3-ubyte.gz to ./data/MNIST/raw

Downloading http://yann.lecun.com/exdb/mnist/train-labels-idx1-ubyte.gz
Downloading http://yann.lecun.com/exdb/mnist/train-labels-idx1-ubyte.gz to ./data/MNIST/raw/train-labels-idx1-ubyte.gz
29696it [00:00, 1419548.81it/s]
Extracting ./data/MNIST/raw/train-labels-idx1-ubyte.gz to ./data/MNIST/raw

Downloading http://yann.lecun.com/exdb/mnist/t10k-images-idx3-ubyte.gz
Downloading http://yann.lecun.com/exdb/mnist/t10k-images-idx3-ubyte.gz to ./data/MNIST/raw/t10k-images-idx3-ubyte.gz
1649664it [00:00, 2005134.07it/s]
Extracting ./data/MNIST/raw/t10k-images-idx3-ubyte.gz to ./data/MNIST/raw

Downloading http://yann.lecun.com/exdb/mnist/t10k-labels-idx1-ubyte.gz
Downloading http://yann.lecun.com/exdb/mnist/t10k-labels-idx1-ubyte.gz to ./data/MNIST/raw/t10k-labels-idx1-ubyte.gz
5120it [00:00, 19575967.62it/s]
Extracting ./data/MNIST/raw/t10k-labels-idx1-ubyte.gz to ./data/MNIST/raw

Processing...
/home/zjl/miniconda3/envs/env_slash/lib/python3.6/site-packages/torchvision/datasets/mnist.py:502: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  /opt/conda/conda-bld/pytorch_1616554789074/work/torch/csrc/utils/tensor_numpy.cpp:143.)
  return torch.from_numpy(parsed.astype(m[2], copy=False)).view(*s)
Done!
Traceback (most recent call last):
  File "slash_mnist_addition.py", line 39, in <module>
    train.slash_mnist_addition(exp_name, experiments[exp_name])
  File "/home/zjl/github/SLASH/src/experiments/mnist_addition/train.py", line 114, in slash_mnist_addition
    mnist_addition_dataset = MNIST_Addition(torchvision.datasets.MNIST(root='./data/', train=True, download=True, transform=transform), 'data/labels/train_data.txt', exp_dict['use_spn'])
  File "/home/zjl/github/SLASH/src/experiments/mnist_addition/dataGen.py", line 12, in __init__
    with open(examples) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/labels/train_data.txt'

**Comment by zdx3578** [comment]
https://github.com/askrix/SLASH#12-anaconda    using conda create env

**Comment by zdx3578** [comment]
should this file   https://github.com/azreasoners/NeurASP/blob/master/examples/mnistAdd/data/train_data.txt
